### ISSUE TITLE
没有处理udp发上来的视频流的数据

### ISSUE THREAD

**Issue by wujincheng2333** [lutongzero/gb28181#2]
大佬，没有处理udp发上来的视频流的数据吗

**Comment by lutongzero** [comment]
多媒体服务器直接用nginx，添加rtmp模块

**Comment by wujincheng2333** [comment]
@lutongzero 这个不是rtmp协议，接不了

**Comment by lutongzero** [comment]
udp是传输协议，应用层协议是rtp。我可以发你抓包信息，你可以对照看看

**Comment by wujincheng2333** [comment]
@lutongzero 有没有java实现的参考文章，现在想转rtsp流

**Comment by lixiaochun** [comment]
28181 相机侧应该过来的是rtp PS流，需要封装成RTMP 发给媒体服务器，实现媒体多路分发吧？

**Comment by wujincheng2333** [comment]
@lixiaochun 封装成rtsp，现在接收ps流数据保存为文件播放花屏，不知道怎么解析流

**Comment by lutongzero** [comment]
抓流和转换可以用ffmpeg抓。国内还有一些开源流媒体服务器，像srs,EasyDarwin。还没测试，.我还没想好怎么抓和分发，不知道性能如何。

**Comment by wujincheng2333** [comment]
@lutongzero 不是拉流问题，现在是gb28181转rtsp的问题，这个能转成功，其他就方便多了

**Comment by qinqi** [comment]
可以使用zlmediakit，国人写的，直接可以接收gb28181的rtp流出flv或者rtmp

**Comment by lixiaochun** [comment]
zlmediakit 是C++的， 楼主是用java写的，集成起来不是太方便。

**Comment by lixiaochun** [comment]
@lutongzero 楼主， javaCV是高度封装了ffmpeg，rtplib也有java版的，是不是可以用rtplib收281818 PS流，再用javaCV 将PS流转成其他RTSP/RTMP等格式，再发给媒体服务器分发呢？

**Comment by qinqi** [comment]
不需要 你直接用netty 接收rtp ps 然后转封装成flv 用 http chunk 传给前端就好了。

**Comment by qinqi** [comment]
我们那套就是这么做的 鉴于公司有规定所以无法开源 并且公司那套代码很乱也没法开源还得整理

**Comment by wujincheng2333** [comment]
@qinqi 我看了下这个zlmediakit ，rtp相关的文档基本没有，大部分都在说rtsp和rtmp的。。。不过看介绍支持gb28181...

**Comment by lutongzero** [comment]
理论上信令服务器和流媒体服务器是分开的，信令服务器一台就好，流媒体服务器看需求，不涉及语言的问题。自己用netty拆包ps应该是可行的，有空实验下。我只是实现了用vlc播放而已，还没到解码转码

**Comment by lixiaochun** [comment]
@qinqi 兄台提的建议非常好，C++版本jrtplib采用线程主动轮询的方式来收RTP流的，这种方式效率较低，视频并发路数上去的话，必须改造成epoll异步IO的方式来收RTP流，程序才能扛得住。
1) 对于java来说，netty天然支持异步IO，通过netty来收RTP流，这个想法非常棒。
2)"接收rtp ps 然后转封装成flv" -- 这种方式可以有，但应该不支持转码，如果要转码的话，就要用到java版本的ffmpeg来实现了吧
3)"用 http chunk 传给前端"  -- 这种方式可以有，但是如果涉及到视频多路转发的话，要么程序自行实现，要么就要借助外置媒体服务器来实现了吧

**Comment by lixiaochun** [comment]
@qinqi HTTP TRUNK这种方式直接推FLV给前端的话，前端播放器也要自己定制开发吧？如果用标准的flv.js啥的，能正常收服务器推送的FLV并播放出来吗？

**Comment by qinqi** [comment]
所有的传输协议 都是基于http chunked 去分发的

**Comment by qinqi** [comment]
不需要 只要普通videojs 或者 flvjs 就可以播放

**Comment by qinqi** [comment]
转封装不需要基于ffmpeg去实现 可以自己手动转封装

**Comment by wujincheng2333** [comment]
@qinqi 大佬，有没有解析rtp ps流的相关文档，百度上的都说一半，弄出来的都是花屏的

**Comment by lixiaochun** [comment]
@qinqi 那这个牛掰了，转码、分发啥的都是自研实现的，牛！

**Comment by qinqi** [comment]
rfc3550 是 rtp ps协议的文档 你去百度一下 就可以

**Comment by wujincheng2333** [comment]
@lutongzero 大佬，你这个sip支持公网和内网之间通讯吗

**Comment by lixiaochun** [comment]
@qinqi  videojs只能播放RTMP/HLS格式视频流，flv.js可以播放HTTP FLV格式视频流。
如果后端基于netty HTTP trunk方式不断生成HTTP FLV，然后前端flv.js主动拉流播放，不是服务器端推流给前端，不知理解对不？

**Comment by lutongzero** [comment]
> @lutongzero 大佬，你这个sip支持公网和内网之间通讯吗

这个需要rprot和received机制吧，还没条件测试

**Comment by wujincheng2333** [comment]
@lutongzero 已经搞定了，自己使用udp服务器实现sip协议栈，然后根据keeplive信息保活公网端口，然后建立一个集合维护
